drop extension if exists "pg_net";

alter table "public"."healthcheck" drop column "updated_at";

alter table "public"."healthcheck" add column "created_at" timestamp with time zone not null default now();

alter table "public"."healthcheck" alter column "id" add generated by default as identity;

alter table "public"."healthcheck" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."knowledge_base" enable row level security;

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant delete on table "public"."conversations" to "anon";

grant insert on table "public"."conversations" to "anon";

grant select on table "public"."conversations" to "anon";

grant update on table "public"."conversations" to "anon";

grant delete on table "public"."conversations" to "authenticated";

grant insert on table "public"."conversations" to "authenticated";

grant select on table "public"."conversations" to "authenticated";

grant update on table "public"."conversations" to "authenticated";

grant delete on table "public"."conversations" to "service_role";

grant insert on table "public"."conversations" to "service_role";

grant select on table "public"."conversations" to "service_role";

grant update on table "public"."conversations" to "service_role";

grant delete on table "public"."healthcheck" to "anon";

grant insert on table "public"."healthcheck" to "anon";

grant select on table "public"."healthcheck" to "anon";

grant update on table "public"."healthcheck" to "anon";

grant delete on table "public"."healthcheck" to "authenticated";

grant insert on table "public"."healthcheck" to "authenticated";

grant select on table "public"."healthcheck" to "authenticated";

grant update on table "public"."healthcheck" to "authenticated";

grant delete on table "public"."healthcheck" to "service_role";

grant insert on table "public"."healthcheck" to "service_role";

grant select on table "public"."healthcheck" to "service_role";

grant update on table "public"."healthcheck" to "service_role";

grant delete on table "public"."itineraries" to "anon";

grant insert on table "public"."itineraries" to "anon";

grant select on table "public"."itineraries" to "anon";

grant update on table "public"."itineraries" to "anon";

grant delete on table "public"."itineraries" to "authenticated";

grant insert on table "public"."itineraries" to "authenticated";

grant select on table "public"."itineraries" to "authenticated";

grant update on table "public"."itineraries" to "authenticated";

grant delete on table "public"."itineraries" to "service_role";

grant insert on table "public"."itineraries" to "service_role";

grant select on table "public"."itineraries" to "service_role";

grant update on table "public"."itineraries" to "service_role";

grant delete on table "public"."knowledge_base" to "anon";

grant insert on table "public"."knowledge_base" to "anon";

grant select on table "public"."knowledge_base" to "anon";

grant update on table "public"."knowledge_base" to "anon";

grant delete on table "public"."knowledge_base" to "authenticated";

grant insert on table "public"."knowledge_base" to "authenticated";

grant select on table "public"."knowledge_base" to "authenticated";

grant update on table "public"."knowledge_base" to "authenticated";

grant delete on table "public"."knowledge_base" to "service_role";

grant insert on table "public"."knowledge_base" to "service_role";

grant select on table "public"."knowledge_base" to "service_role";

grant update on table "public"."knowledge_base" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


